name: data_supabase
description: "The supabase data layer shared across all apps"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  json_annotation: ^4.12.0
  supabase_flutter: ^2.15.0
  uuid: ^4.5.3

  domain:
    path: ../domain
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  json_serializable: ^6.14.0

flutter:
